name: Assignment-1
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Check out repo        
      uses: actions/checkout@v2
    - name: JFrog CLI
      # You may pin to the exact commit or the version.
      # uses: Deepakanandrao/jfrog-cli@25346328751ee784df9acb5911fdf3858805fa35
      uses: Deepakanandrao/jfrog-cli@v3
      with:
        # Jfrog Artifactory cli command e.g.  `jfrog rt ping`
        cli_cmd: jfrog rt ping



