name: Assignment-1
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Check out repo        
      uses: actions/checkout@v2

        
    - name: Ping Artifactory
      uses: katcosgrove/jfrog-actions@master
      with:
          cmd: 'ping'
      env:
          auth: user
          USER: admin
          PASS: 27Vaibhav2000
          url: localhost:8082/ui/login
