name: Assignment-1
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Check out repo        
      uses: actions/checkout@v2
    - run: ./test.sh
    - name: publish to artifactory
      uses: advancedcsg-open/action-jfrog-cli@master
      with:
        url: 'http://localhost:8082/'
        credentials type: 'username'
        user: 'admin'
        password: '27Vaibhav2000'
        
