name: Assignment-1
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Check out repo        
      uses: actions/checkout@v2
    - run: |
            chmod +x test.sh
            ./test.sh
    - name: publish to artifactory
      run: |
            pwd
            ls
