name: Assignment-1
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Check out repo        
      uses: actions/checkout@v2
    - run: |
            chmod +x test.sh
            ./test.sh
    - name: publish to artifactory
      run: |
            curl -u admin:27Vaibhav2000 -T "" "http://localhost:8081/artifactory/example-repo-local/vaibhav"
